import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
// import StyledComponentsRegistry from "../lib/AntdRegistry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Saylani Fasion Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
